//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public Movie()
        {
            this.Screening = new HashSet<Screening>();
        }
    
        public int MovieId { get; set; }
        public string Title { get; set; }
        public string AgeLimit { get; set; }
        public int RunTime { get; set; }
        public string Genre { get; set; }
        public string Year { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Screening> Screening { get; set; }
    }
}
