//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salon
    {
        public Salon()
        {
            this.Screening = new HashSet<Screening>();
        }
    
        public int SalonId { get; set; }
        public int Seats { get; set; }
    
        public virtual ICollection<Screening> Screening { get; set; }
    }
}
