//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Screening
    {
        public Screening()
        {
            this.Booking = new HashSet<Booking>();
        }
    
        public int ScreeningId { get; set; }
        public Nullable<int> MovieId { get; set; }
        public Nullable<int> SalonId { get; set; }
        public System.DateTime StartDateTime { get; set; }
    
        public virtual ICollection<Booking> Booking { get; set; }
        public virtual Movie Movie { get; set; }
        public virtual Salon Salon { get; set; }
    }
}
